/* TABLE IF EXISTS  Deletion statements for MySQL */

DROP TABLE IF EXISTS  SEMANTIC_OBSERVATION CASCADE ;

DROP TABLE IF EXISTS  USER_GROUP_MEMBERSHIP  CASCADE;

DROP TABLE IF EXISTS  USER_GROUP  CASCADE;

DROP TABLE IF EXISTS  USER  CASCADE;

DROP TABLE IF EXISTS  INFRASTRUCTURE  CASCADE;





